name: MACOS11

on: [push, workflow_dispatch]
  
jobs:

  build:
  
    runs-on: macos-10.15

    steps:

      - uses: actions/checkout@v3
          
      - name: compiling ... 
          
        run: |
          cd /Users/runner/work/PhysX/PhysX
          bash ./Actions/BigSur/RUNNER.sh
          
          
      - name: Saving Artifacts ...
        uses: actions/upload-artifact@v2
        with:
          name: FromContainer
          if-no-files-found: warn #  'error'  'warn'  'ignore' 
          path: ./PhysX.tar 
          retention-days: 1
          
          
