name: MACOS11

on: [push, workflow_dispatch]
  
jobs:

  build:
  
    runs-on: macos-10.15

    steps:

      - uses: actions/checkout@v3
          
      - name: runner... 
          
        run: |
          cd /Users/runner/work/PhysX/PhysX
          ls -la 
          bash ./Actions/BigSur/RUNNER.sh
          
